### ISSUE TITLE
"errorMessage": "Cannot find module 'request'",

### ISSUE THREAD

**Issue by piiot** [jethrocarr/lambda-ping#5]
```
Response:
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'request'",
  "trace": [
    "Error: Cannot find module 'request'",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)",
    "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72748)",
    "    at require (internal/modules/cjs/helpers.js:25:18)",
    "    at module.exports.http (/var/task/handler.js:8:18)",
    "    at Runtime.handler (/var/task/serverless_sdk/index.js:9:137040)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}

Request ID:
"3751f4ca-3a52-4139-a22f-ca6a721e5415"

Function Logs:
START RequestId: 3751f4ca-3a52-4139-a22f-ca6a721e5415 Version: $LATEST
2020-05-24T20:38:19.477Z	3751f4ca-3a52-4139-a22f-ca6a721e5415	INFO	
2020-05-24T20:38:19.498Z	3751f4ca-3a52-4139-a22f-ca6a721e5415	ERROR	{ Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72748)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports.http (/var/task/handler.js:8:18)
    at Runtime.handler (/var/task/serverless_sdk/index.js:9:137040)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25) code: 'MODULE_NOT_FOUND' }
2020-05-24T20:38:19.897Z	3751f4ca-3a52-4139-a22f-ca6a721e5415	INFO	SERVERLESS_ENTERPRISE {"c":true,"b":"H4sIAAAAAAAAA+0Ya3PaxvavbDWdWzuD3g8kct2pi0maxEl9DbnJxHiYRVqBYmlX3V1hSMb/vWclAYYY3+vM9FPLF7TnnD3vl/RVYzybZVTraSIXOp4RKrWOJuI5KfB/CRcZUzjLsAAqs4IIiYsSII7lWLrl6443cqyeG/bsyAij4BOQcfJHBXSvEiBzu76dejHWXew7ume7kY4dJ9VjHOCuYxPfs33FeVUSoCacMw7HEq9yhuH+11aTUYMXuigxPagfKwnHEiDvcNGQS46pwLGC6WlF6wd1XWIuR1lN9JAhnl0bQmjyCFFrbVI1MrWe242MyOt6kQ8SQM8+o5IspbIC9IjJUxyi7tf0qRUHgZ8EOrZ9X/ciTPTQTS2963mB03Ude5oSoF+ONhIuGZMntu6TGCdTF+ueQyzLISGxSeinoRUQ3LUCJ3x+gTlE+8QNfNvzYzfoBvY0csPnQ4hwTpITS7uDyOCZeCAOhxz7XXnTupvxmTKAVnne0XBZ5ll8P5o5LqYJ1suMzpQkwhdZTFrcGgjarkEJWQBkrds9Oh0w+lzKstWMVRAi1+poMSvKSpLWRnwrjEaktkFdVlQ2CbHFGpQl5LMwbMtwGnPXxGTWOKES+i3Yrztb3FtSML4aZl8UL9sJ9zHvBVGh/DrWuBBjree5QRQAXWeszQkuR0ziHMC27/mha3ktWN1SUNuzuk4UABTSj3Ba03bt0LLDu31JF4THkAXgt0ZmaPgR5OiGSiUxzijh78vGdDDT3WBfiT7Lk6EqJ60neUW2GArBoJCSdMGaMPYZeA+027KuhGTFcDexWpwODtb33X//wn6O7ZC8eDzqD9JuGf54fjoaDEf7hKdcITGnPdCt1+jW28S2F9lR6EeRZ3tOt7dOu96joh/LkIbicJ40eOXdG7Ktml2Fb8Xl01vxDouPf0lb2RNyzmYvOavKNlomuNds3Gs+6j64N5Sc4KK9qFqLafmm45lXbQyvu7EVxWnqJaEVQ2PGUxtjJ8FdsMp3wzDZ5zmgi4scy5TxQrWcjFbLB0hOeTwH9DLwHkA2MatLFLI96lpR5DvWIboXnIDufuA6ngUl+w1Vv6yg/2pX0AoKaDSqksfaKxgs+dHlMfpIGFX/F5zFRAjG0S/IMXzr5W9fxhrUvyhJ3RIc37LgWDdiOAKzChroFkGhlcJJPYpV03BqeJbkCu44LnSZBsL/UIR3d52/SKPoYYUcb1+hwN9V6FpN7AWkXttLKnpD2S3dQP/nEOp+WtMOWQVdcV1UNajtPapRboZLva7UxTFQTz/82MeUMonSjCYIfFPlBP3UbkM/relf4DoxmmZZQ/pVXvIMWqM2UcQZJwYz2id0pAYd4Tn4ciKSGxNYk6XxWRyv+Q2WMSlVr2nNHrQ71C7yLdxvVP9/dNxcA3vjm3p5aXMwzXJCodzqoB9QrY4zlA6hTMUTDut2WN/61sj2wpRjvpqkvGGf4lwQgOOpmJRYzuu75gJzU2JxYz4mu+RkEjfLF9y6GmvoGfoVw3hDjKL3QMlFzECBzwLZRmi46N+qvfRMs9rgYKDDOmKev+oP3g0HP9dsgUuflSvYl+cSvSacFCt0KuY34BDRQWcsrgqVKDmrEoTBu9CcwanZDKbfgqBLUjIO01igf6FBkknGQdlrYNtqOlEeq41Ez8yjtceOjr+CyYidjMdjbbAsSSzBDIw2HgVwJ6uxk0nOEizmkzKHeM1hLhM+mdQE4uTqSj2Af+szTJLrTg2ZguMa0AbQuJAJuetD89kPay+cEbCjAHVRloKliE0/g14oE6DYr1Waqjq+rhvETrrMwSk54d9kSLifIU1aGmSpPCYMFZzvSZE9ed9mBTJN9IEgaDxIzglScgRkwe3trUHLAlIAmrFZQgVA5ZhtjaD2jGBEIGgT6LfR6KJxjGIX4zwXSGSw+aBMogLfEAHMYYwBlCGCxco4FHakIr0Wg05QWx1Hm/I8fn4gNlv5I7Dj9MMQDc/eqHiIeVaWKmEE6M0lYmlt6Xk9XRGhi4wzqrLWUI6g0JqV1hl9MH7fV+7tzmy00fin1v8WtV4HjzehN9cpsJ8rQbCfLE2S/E7jp86EA6IeqHn1g4IUxkQQeUZSXOVysMzkeSYkgfeco6zeqduXdyNrN+y29g7WrvrlRELRCmAI1VvLaJP+6ICfUft7Pfz9nQEFKsjRlCWr14LR405b1M1vVyksYS7PB9vyPYOl4kj1nil0p5ZKcbiut6J7L+tP+aYA7sC0eXfIFvA0ZwUWrjsrcK7Q8Ib+PlPIaBh6Lz68fRflzpf+zBf1ztVcbgheR4s3n974QZKKty8vXfc/H9U3nryaZffeulwjMGz1AiTV5jwsQWW1/z3108ldR8tZ/cnirvmKAo9X1+sdsP6YcXV9d/cnTBpP5PgSAAA=","origin":"sls-agent"}
2020-05-24T20:38:19.935Z	3751f4ca-3a52-4139-a22f-ca6a721e5415	ERROR	Invoke Error	{"errorType":"Error","errorMessage":"Cannot find module 'request'","code":"MODULE_NOT_FOUND","stack":["Error: Cannot find module 'request'","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)","    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:72748)","    at require (internal/modules/cjs/helpers.js:25:18)","    at module.exports.http (/var/task/handler.js:8:18)","    at Runtime.handler (/var/task/serverless_sdk/index.js:9:137040)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: 3751f4ca-3a52-4139-a22f-ca6a721e5415
REPORT RequestId: 3751f4ca-3a52-4139-a22f-ca6a721e5415	Duration: 553.29 ms	Billed Duration: 600 ms	Memory Size: 128 MB	Max Memory Used: 75 MB	Init Duration: 220.46 ms	
```

**Comment by soareseds** [comment]
I'm facing the same error, any update on it guys?

**Comment by spuggy** [comment]
I think you have to do an npm install before deploying
